
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import AggregatedDataFeedStoreContractArtifactJson from './adfs_contract-AggregatedDataFeedStore.json' with { type: 'json' };
export const AggregatedDataFeedStoreContractArtifact = loadContractArtifact(AggregatedDataFeedStoreContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract AggregatedDataFeedStore;
 */
export class AggregatedDataFeedStoreContract extends ContractBase {

  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, AggregatedDataFeedStoreContractArtifact, wallet);
  }



  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, AggregatedDataFeedStoreContract.artifact, wallet) as Promise<AggregatedDataFeedStoreContract>;
  }


  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet,) {
    return new DeployMethod<AggregatedDataFeedStoreContract>(PublicKeys.default(), wallet, AggregatedDataFeedStoreContractArtifact, AggregatedDataFeedStoreContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet,) {
    return new DeployMethod<AggregatedDataFeedStoreContract>(publicKeys, wallet, AggregatedDataFeedStoreContractArtifact, AggregatedDataFeedStoreContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AggregatedDataFeedStoreContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<AggregatedDataFeedStoreContract['methods'][M]>
  ) {
    return new DeployMethod<AggregatedDataFeedStoreContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      AggregatedDataFeedStoreContractArtifact,
      AggregatedDataFeedStoreContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }



  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AggregatedDataFeedStoreContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(AggregatedDataFeedStoreContractArtifactJson as NoirCompiledContract);
  }






  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {

    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_2_slots_at_index(feed_id: field, index: field, start_slot: field) */
    get_2_slots_at_index: ((feed_id: FieldLike, index: FieldLike, start_slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_2_slots_latest_index(feed_id: field, start_slot: field) */
    get_2_slots_latest_index: ((feed_id: FieldLike, start_slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_4_slots_at_index(feed_id: field, index: field, start_slot: field) */
    get_4_slots_at_index: ((feed_id: FieldLike, index: FieldLike, start_slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_4_slots_latest_index(feed_id: field, start_slot: field) */
    get_4_slots_latest_index: ((feed_id: FieldLike, start_slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_8_slots_at_index(feed_id: field, index: field, start_slot: field) */
    get_8_slots_at_index: ((feed_id: FieldLike, index: FieldLike, start_slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_8_slots_latest_index(feed_id: field, start_slot: field) */
    get_8_slots_latest_index: ((feed_id: FieldLike, start_slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_as_much_latest_sliced_data(feed_id: field, start_slot: field, slots: field) */
    get_as_much_latest_sliced_data: ((feed_id: FieldLike, start_slot: FieldLike, slots: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_as_much_sliced_data_at_index(feed_id: field, index: field, start_slot: field, slots: field) */
    get_as_much_sliced_data_at_index: ((feed_id: FieldLike, index: FieldLike, start_slot: FieldLike, slots: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_block_number() */
    get_block_number: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_data_at_index(feed_id: field, index: field) */
    get_data_at_index: ((feed_id: FieldLike, index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_latest_1_slot_data(feed_id: field, start_slot: field) */
    get_latest_1_slot_data: ((feed_id: FieldLike, start_slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_latest_data(feed_id: field) */
    get_latest_data: ((feed_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_latest_data_and_index(feed_id: field) */
    get_latest_data_and_index: ((feed_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_latest_index(feed_id: field) */
    get_latest_index: ((feed_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_feeds(feed_input_data: array, feeds_len: integer, indices_len: integer, block_number: integer) */
    update_feeds: ((feed_input_data: FieldLike[], feeds_len: (bigint | number), indices_len: (bigint | number), block_number: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };


}
