[
  # API keys
  "CMC_API_KEY"
  "YF_FINANCE_API_KEY"
  "APCA_API_KEY_ID"
  "APCA_API_SECRET_KEY"
  "ALPHAVANTAGE_API_KEY"
  "YAHOO_FINANCE_API_KEY"
  "TWELVEDATA_API_KEY"
  "FMP_API_KEY"
  "SPOUT_RWA_API_KEY"
  "METALS_API_KEY"

  # URLs
  "RPC_URL_INK_SEPOLIA"
  "RPC_URL_ETHEREUM_SEPOLIA"
]
