[package]
name = "uatu"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
scraper = "0.13"
mysql = "25.0.1"
