spin_manifest_version = 2

[application]
authors = ["Yordan Madzhunkov"]
name = "GeckoTerminal dex prices"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 10
sequencer = "http://127.0.0.1:9856/post_reports_batch"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
reporter_id = 0

[[trigger.oracle]]
component = "gecko-terminal"

[[trigger.oracle.data_feeds]]
id = "100000"
data = '{"network":"monad-testnet", "pool":"0x264e9b75723d75e3c607627d8e21d2c758db4c80", "reverse": true}'


[component.gecko-terminal]
source = "../../../target/wasm32-wasip1/release/gecko_terminal.wasm"

allowed_outbound_hosts = ["https://app.geckoterminal.com/"]

[component.gecko-terminal.build]
command = "cargo build --target wasm32-wasip1 --release"
