spin_manifest_version = 2

[application]
authors = ["Yordan Madzhunkov"]
name = "Etherium RPC"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 10
reporter_id = 0
sequencer = "http://127.0.0.1:8877/post_reports_batch"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
second_consensus_secret_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
kafka_endpoint = "http://127.0.0.1:9092"

[[trigger.oracle]]
component = "eth-rpc"

[[trigger.oracle.data_feeds]]
id = "1"
stride = 0
decimals = 0
data = '{"pair":{"base":"ynETHx","quote":"WETH"},"decimals":0,"category":"","market_hours":"Crypto","arguments":{"contracts":[{"address":"0x7b883191011AEAe40581d3Fa1B112413808C9c00","label":"a","method_name":"getReservesData","param1":"1000000000000000000","rpc_urls":["https://rpc.hyperliquid.xyz/evm"]}]}}'

[component.eth-rpc]
source = "../target/wasm32-wasip1/release/eth_rpc.wasm"
allowed_outbound_hosts = [
  "https://eth.llamarpc.com",
  "https://rpc.eth.gateway.fm",
  "https://ethereum-rpc.publicnode.com",
  "https://binance.llamarpc.com",
  "https://bsc.meowrpc.com",
  "https://bsc.drpc.org",
  "https://arbitrum-one-rpc.publicnode.com",
  "https://rpc.hyperliquid.xyz",
]

[component.eth-rpc.build]
command = "cargo build --target wasm32-wasip1 --release"
