spin_manifest_version = 2

[application]
authors = ["Yordan Madzhunkov"]
name = "Etherium RPC"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 90
reporter_id = 0
sequencer = "http://127.0.0.1:8877/post_reports_batch"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
second_consensus_secret_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
kafka_endpoint = "http://127.0.0.1:9092"

[[trigger.oracle]]
component = "eth-rpc"

[[trigger.oracle.data_feeds]]
id = "100001"
stride = 0
decimals = 0
data = '{"pair":{"base":"ynETHx","quote":"WETH"},"decimals":0,"category":"","market_hours":"Crypto","arguments":{"contracts":[{"address":"0x657d9ABA1DBb59e53f9F3eCAA878447dCfC96dCb","label":"ynETHx","method_name":"convertToAssets","param1":"1000000000000000000","rpc_urls":["https://eth.llamarpc.com","https://rpc.eth.gateway.fm","https://ethereum-rpc.publicnode.com"]}]}}'

[[trigger.oracle.data_feeds]]
id = "100002"
stride = 0
decimals = 0
data = '{"pair":{"base":"YUSD","quote":"USDC"},"decimals":0,"category":"","market_hours":"Crypto","arguments":{"contracts":[{"address":"0x19Ebd191f7A24ECE672ba13A302212b5eF7F35cb","label":"YieldFi yUSD","method_name":"exchangeRate","rpc_urls":["https://eth.llamarpc.com","https://rpc.eth.gateway.fm","https://ethereum-rpc.publicnode.com"]}],"divisor":1000000}}'

[[trigger.oracle.data_feeds]]
id = "100003"
stride = 0
decimals = 0
data = '{"pair":{"base":"ynBNBx","quote":"WBNB"},"decimals":0,"category":"","market_hours":"Crypto","arguments":{"contracts":[{"address":"0x32c830f5c34122c6afb8ae87aba541b7900a2c5f","label":"yBNBx","method_name":"convertToAssets","param1":"1000000000000000000","rpc_urls":["https://binance.llamarpc.com","https://bsc.meowrpc.com","https://bsc.drpc.org"]}]}}'

[[trigger.oracle.data_feeds]]
id = "100004"
stride = 0
decimals = 0
data = '{"pair":{"base":"oLP","quote":"USDC"},"decimals":0,"category":"","market_hours":"Crypto","arguments":{"contracts":[{"address":"0x20d419a8e12c45f88fda7c5760bb6923cee27f98","label":"oLP","method_name":"convertToAssets","param1":"1000000000000000000","rpc_urls":["https://arbitrum-one-rpc.publicnode.com"]}]}}'

[component.eth-rpc]
source = "../target/wasm32-wasip1/release/eth_rpc.wasm"
allowed_outbound_hosts = [
  "https://eth.llamarpc.com",
  "https://rpc.eth.gateway.fm",
  "https://ethereum-rpc.publicnode.com",
  "https://binance.llamarpc.com",
  "https://bsc.meowrpc.com",
  "https://bsc.drpc.org",
  "https://arbitrum-one-rpc.publicnode.com",
]

[component.eth-rpc.build]
command = "cargo build --target wasm32-wasip1 --release"
