package blocksense:oracle@2.0.0;

world blocksense-oracle {
  record test {
    str: str,
  }

  record str {
    string1: string,
    union: list<list<union>, 2>,
  }

  variant union {
    none,
    integer(u32),
    string2(string),
  }
}
