package blocksense:oracle@2.0.0;

interface oracle-types {
  record test {
    union: union,
  }

  variant union {
    none,
    integer(u32),
    str1(string),
    struct2(struct2),
  }

  record struct2 {
    str2: list<string>,
  }
}

world blocksense-oracle {
  use oracle-types.{test};
  export handle-oracle-request: func() -> result<test>;
}
