checksumBehavior: ignore

plugins:
  - checksum: e183406dae0b56ce2dcf0880f6b4f8dd4bd1a50ebc8e06f37f05c375dae351476019a3c324443c1b9fa5ed0b3ad2053fae39810d66c16d84c4fc0365f531e650
    path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: 'https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js'

pnpEnableEsmLoader: true

nixExprPath: nix/pkgs/yarn/yarn-project.generated.nix
generateDefaultNix: false
enableNixPreload: false
individualNixPackaging: false

logFilters:
  # https://yarnpkg.com/advanced/error-codes
  - code: YN0007
    level: discard
    # (MUST_BUILD)
  - code: YN0013
    level: discard
    # (FETCH_NOT_CACHED)
  - code: YN0076
    level: discard
    # (INCOMPATIBLE_ARCHITECTURE)

packageExtensions:
  '@typescript-eslint/utils@*':
    dependencies:
      eslint: '8'

  'eslint-config-next@*':
    dependencies:
      next: '*'

  'next@^15':
    dependencies:
      nextra: '4.0.0'
      nextra-theme-docs: '4.0.0'

  'langium@*':
    dependencies:
      '@chevrotain/regexp-to-ast': '11.0.3'
      vscode-languageserver: '9.0.1'
      vscode-languageserver-protocol: '3.17.5'
      vscode-languageserver-types: '3.17.5'
      vscode-jsonrpc: '8.2.0'

  'acorn-jsx@*':
    dependencies:
      acorn: '*'

  '@aztec/foundation@0.55.1':
    dependencies:
      'tslib': '^2.6.3'

  '@aztec/circuit-types@0.55.1':
    dependencies:
      'viem': '^2.20.0'

  '@storybook/nextjs@8.6.12':
    dependencies:
      'next': '15.1.4'
      'webpack': '5.98.0'

  'postcss-loader@*':
    dependencies:
      '@tailwindcss/postcss': '*'

  '@walletconnect/modal-ui@*':
    dependencies:
      'lit-html': '^3.3.0'

  'pino@*':
    dependencies:
      'pino-pretty': '*'

  '@effect/eslint-plugin@*':
    dependencies:
      '@typescript-eslint/utils': '*'

  '@vitejs/plugin-react@4.3.4':
    dependencies:
      'vite': '^7'

  '@ethers-ext/signer-ledger@*':
    dependencies:
      'tslib': '*'
