checksumBehavior: ignore

packageExtensions:
  '@aztec/circuit-types@0.55.1':
    dependencies:
      viem: ^2.20.0
  '@aztec/foundation@0.55.1':
    dependencies:
      tslib: ^2.6.3
  '@storybook/nextjs@8.6.12':
    dependencies:
      next: 15.1.4
      webpack: 5.98.0
  '@typescript-eslint/utils@*':
    dependencies:
      eslint: 8
  '@walletconnect/modal-ui@*':
    dependencies:
      lit-html: ^3.3.0
  acorn-jsx@*:
    dependencies:
      acorn: '*'
  eslint-config-next@*:
    dependencies:
      next: '*'
  langium@*:
    dependencies:
      '@chevrotain/regexp-to-ast': 11.0.3
      vscode-jsonrpc: 8.2.0
      vscode-languageserver: 9.0.1
      vscode-languageserver-protocol: 3.17.5
      vscode-languageserver-types: 3.17.5
  next@^15:
    dependencies:
      nextra: 4.0.0
      nextra-theme-docs: 4.0.0
  pino@*:
    dependencies:
      pino-pretty: '*'
  postcss-loader@*:
    dependencies:
      '@tailwindcss/postcss': '*'

plugins:
  - checksum: 49c16cbcf9ebdb2869f3a1fbc187e22f071047cff5ecc24e1df838aeaad40743b65a8702da0b308cc8568852f10a6653fa1b1a2c22bef36700ed96b1454289d5
    path: .yarn/plugins/@yarnpkg/plugin-nix-berry.cjs
    spec: libs/ts/nix-berry/bundles/@yarnpkg/plugin-nix-berry.js
