checksumBehavior: ignore

yarnPath: .yarn/releases/yarn-4.3.1.cjs

nodeLinker: pnp

packageExtensions:
  '@aztec/foundation@0.52.0':
    dependencies:
      'tslib': '^2.6.3'
  '@aztec/circuit-types@0.52.0':
    dependencies:
      'viem': '^2.20.0'
