checksumBehavior: update

yarnpnp2nixManifestPath: "./nix/pkgs/onchain-interactions/yarn-manifest.generated.nix"

logFilters:
  - code: YN0007
    level: discard
  - code: YN0013
    level: discard
  - code: YN0076
    level: discard

packageExtensions:
  "@aztec/circuit-types@0.55.1":
    dependencies:
      viem: ^2.20.0
  "@aztec/foundation@0.55.1":
    dependencies:
      tslib: ^2.6.3
  "@effect/eslint-plugin@*":
    dependencies:
      "@typescript-eslint/utils": "*"
  "@ethers-ext/signer-ledger@*":
    dependencies:
      tslib: "*"
  "@storybook/nextjs@8.6.12":
    dependencies:
      next: 15.1.4
      webpack: 5.98.0
  "@typescript-eslint/utils@*":
    dependencies:
      eslint: 8
  "@vitejs/plugin-react@4.3.4":
    dependencies:
      vite: ^7
  "@walletconnect/modal-ui@*":
    dependencies:
      lit-html: ^3.3.0
  acorn-jsx@*:
    dependencies:
      acorn: "*"
  eslint-config-next@*:
    dependencies:
      next: "*"
  langium@*:
    dependencies:
      "@chevrotain/regexp-to-ast": 11.0.3
      vscode-jsonrpc: 8.2.0
      vscode-languageserver: 9.0.1
      vscode-languageserver-protocol: 3.17.5
      vscode-languageserver-types: 3.17.5
  next@^15:
    dependencies:
      nextra: 4.0.0
      nextra-theme-docs: 4.0.0
  pino@*:
    dependencies:
      pino-pretty: "*"
  postcss-loader@*:
    dependencies:
      "@tailwindcss/postcss": "*"

plugins:
  - checksum: 7f39a417d51984d2cfac5f10ff9cb5ad72754fd7aa07d3093b468c31ed53adbcc5520285f7c74fe8519aa39abe3d8b6731fee8ae3719e252a7d245476d6da7cd
    path: .yarn/plugins/@yarnpkg/plugin-yarnpnp2nix.cjs
    spec: ../yarnpnp2nix/plugin/dist/plugin-yarnpnp2nix.js
