checksumBehavior: ignore

yarnPath: .yarn/releases/yarn-4.3.1.cjs

packageExtensions:
  '@typescript-eslint/utils@*':
    dependencies:
      eslint: '8'

  'eslint-config-next@*':
    dependencies:
      next: '*'

  '@aztec/foundation@0.55.1':
    dependencies:
      'tslib': '^2.6.3'
  '@aztec/circuit-types@0.55.1':
    dependencies:
      'viem': '^2.20.0'
