checksumBehavior: ignore

yarnPath: .yarn/releases/yarn-4.3.1.cjs

packageExtensions:
  '@typescript-eslint/utils@*':
    dependencies:
      eslint: '8'

  'eslint-config-next@*':
    dependencies:
      next: '*'
