[workspace]
members = [
  "apps/reporter",
  "apps/sequencer",
  "apps/sequencer_tests",
  "libs/anomaly_detection",
  "libs/cli",
  "libs/data_feeds",
  "libs/derive",
  "libs/prometheus",
  "libs/registry",
  "libs/sdk",
  "libs/sdk/trigger-oracle",
  "libs/utils",
  "libs/sequencer_config"
, "libs/crypto", "libs/feed_registry"]
resolver = "2"

[workspace.package]
version = "0.1.1"
authors = ["The Blocksense team"]
license = "to be decided"
edition = "2021"
