[workspace]
members = [
  "apps/cli",
  "apps/reporter",
  "apps/sequencer",
  "apps/sequencer_tests",
  "apps/trigger-oracle",
  "libs/anomaly_detection",
  "libs/data_feeds",
  "libs/derive",
  "libs/prometheus",
  "libs/registry",
  "libs/sdk",
  "libs/utils",
  "libs/config",
  "libs/crypto",
  "libs/feed_registry",
  "libs/blockchain_data_model"]
resolver = "2"

[workspace.package]
version = "0.1.1"
authors = ["The Blocksense team"]
license = "to be decided"
edition = "2021"
