[workspace]
members = ["libs/anomaly_detection", "apps/sequencer", "libs/sdk", "libs/sdk/trigger-oracle"]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["The Blocksense team"]
license = "to be decided"
edition = "2021"
