[workspace]
members = [ "apps/reporter","apps/sequencer", "libs/anomaly_detection", "libs/data_feeds","libs/prometheus", "libs/utils"]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["The Blocksense team"]
license = "to be decided"
edition = "2021"
