#FROM alpine:3.18 AS build-environment
FROM ubuntu:24.04 AS build-environment
# ARG TARGETARCH
WORKDIR /opt

RUN apt-get update
#RUN apk add clang lld curl build-base linux-headers git \
#    openssl-dev libusb-dev \
RUN apt-get install -y build-essential git clang curl \
    librust-openssl-dev libusb-dev \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh \
    && chmod +x ./rustup.sh \
    && ./rustup.sh --default-toolchain 1.80.0 -y

# Add .cargo/bin to PATH
ENV PATH="/root/.cargo/bin:${PATH}"


WORKDIR /opt/blocksense
COPY . .


RUN --mount=type=cache,target=/root/.cargo/registry --mount=type=cache,target=/root/.cargo/git --mount=type=cache,target=/opt/blocksense/target \
    RUST_BACKTRACE=1 cargo build --release \
    && mkdir out \
    && mv target/release/launch_reporter out/launch_reporter \
    && strip out/launch_reporter;

RUN cd /opt/blocksense/apps/trigger-oracle \
    && cargo build --release \
    && tar czf "/opt/blocksense/apps/trigger-oracle/trigger-oracle.tar.gz" -C "/opt/blocksense/target/release" ./trigger-oracle


FROM ubuntu:24.04 AS blocksense-reporter
RUN apt-get update
RUN apt-get install -y wget curl build-essential git \
    librust-openssl-dev libusb-dev 

# Install SPIN
RUN curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash -s -- -v v2.7.0

COPY --from=build-environment /opt/blocksense/out/launch_reporter /usr/local/bin/launch_reporter
WORKDIR /usr/local/blocksense


ENV REPORTER_CONFIG_DIR=/usr/local/blocksense/apps/reporter
ENV FEEDS_CONFIG_DIR=/usr/local/blocksense

RUN mkdir -p $REPORTER_CONFIG_DIR
COPY --from=build-environment /opt/blocksense/apps/trigger-oracle/trigger-oracle.tar.gz $REPORTER_CONFIG_DIR/trigger-oracle.tar.gz
COPY config/docker/install_trigger_oracle_in_spin.sh  /opt/blocksense/apps/trigger-oracle/install_trigger_oracle_in_spin.sh
RUN bash -c /opt/blocksense/apps/trigger-oracle/install_trigger_oracle_in_spin.sh


COPY config/docker/reporter_config.json  /usr/local/blocksense/apps/reporter/reporter_config.json
COPY config/docker/reporter_secret_key   /usr/local/blocksense/apps/reporter/reporter_secret_key

ENTRYPOINT ["/bin/sh", "-c", "cd /usr/local/blocksense/oracles/yahoo && /spin up"]
