package blocksense:oracle@2.0.0;

interface oracle-types {
  record payload {
    event-name: string,
    season: string,
    home-team: string,
    away-team: string,
    home-score: u64,
    away-score: u64,
  }
}

world blocksense-oracle {
  use oracle-types.{test};
  export handle-oracle-request: func() -> result<payload>;
}
