spin_manifest_version = 2

[application]
authors = ["Emil Ivanichkov"]
name = "Chicken farm Oracle"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 5
sequencer = "http://127.0.0.1:9856/post_reports_batch"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
second_consensus_secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
kafka_endpoint = "http://127.0.0.1:9092"
reporter_id = 0

[[trigger.oracle]]
component = "chicken-farm"

[[trigger.oracle.data_feeds]]
id = "5000000"
stride = 0
decimals = 6
data = '{"pair":{"base":"supply","quote":"amount"},"decimals":6,"category":"","market_hours":"","arguments":{}}'

[[trigger.oracle.data_feeds]]
id = "50000001"
stride = 0
decimals = 6
data = '{"pair":{"base":"price","quote":"amount"},"decimals":6,"category":"","market_hours":"","arguments":{}}'

[component.chicken-farm]
source = "../target/wasm32-wasip1/release/chicken_farm.wasm"
allowed_outbound_hosts = ["http://localhost"]

[component.chicken-farm.build]
command = "cargo build --target wasm32-wasip1 --release"
