spin_manifest_version = 2

[application]
name = "Blocksense runtime"
version = "0.1.0"
authors = ["blocksense-network"]

[application.trigger.settings]
interval_time_in_seconds = 10
reporter_id = 0
sequencer = "http://127.0.0.1:9856/post_reports_batch"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
second_consensus_secret_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
kafka_endpoint = "http://127.0.0.1:9092"
metrics_url = "http://127.0.0.1:9091"

[[trigger.oracle]]
component = "sports-db"
capabilities = []

[[trigger.oracle.data_feeds]]
id = "0"
stride = 4
decimals = 0
data = '{"pair":null,"decimals":0,"category":"Sports","market_hours":null,"arguments":{"kind":"sports-db","sport_type":"Soccer","team_id":133602}}'

[component.sports-db]
source = "../target/wasm32-wasip1/release/sports_db.wasm"
allowed_outbound_hosts = ["https://www.thesportsdb.com/"]

[component.sports-db.build]
command = "cargo build --target wasm32-wasip1 --release"
