[package]
name = "sequencer"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "6f4e397f7cf71812160a165bdcebf40cac814fef", features = [
    # "dyn-abi",
    # "json-abi",
    # "json",
    "sol-types",
    # "rlp",
    # "serde",
    "contract",
    # "consensus",
    # "eips",
    "network",
    # "genesis",
    "node-bindings",
    "providers",
    "rpc",
    # "json-rpc",
    "rpc-client",
    # "rpc-types",
    "rpc-types-eth",
    # "rpc-types-engine",
    "rpc-types-trace",
    "signers",
    # "signer-aws",
    # "signer-gcp",
    "signer-keystore",
    "signer-ledger",
    "signer-mnemonic",
    "signer-trezor",
    "signer-wallet",
    "signer-yubihsm",
    "transports",
    "transport-http",
    "transport-ipc",
    "transport-ws",
    "pubsub",
] }

reqwest = { version = "0.12", default-features = false }
# async
tokio = { version = "1.4.0", features = ["full"] }

# misc
eyre = "0.6.12"
openssl-sys = "0.9.102"
actix-web = "4.6.0"
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"]}
futures = "0.3.30"
envload = "0.1.1"
once_cell = "1.19.0"
async-channel = "2.3.0"

[[bin]]
name = "sequencer"
path = "bin/sequencer_runner.rs"
