[package]
name = "sequencer"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
data_feeds = { path = "../../libs/data_feeds" }
anomaly_detection = { path = "../../libs/anomaly_detection" }
sequencer_config = { path = "../../libs/sequencer_config" }
crypto = { path = "../../libs/crypto" }
utils = { path = "../../libs/utils" }
feed_registry = { path = "../../libs/feed_registry"}

alloy = { git = "https://github.com/alloy-rs/alloy", rev = "6f4e397f7cf71812160a165bdcebf40cac814fef", features = [
    # "dyn-abi",
    # "json-abi",
    # "json",
    "sol-types",
    # "rlp",
    # "serde",
    "contract",
    # "consensus",
    # "eips",
    "network",
    # "genesis",
    "node-bindings",
    "providers",
    "rpc",
    # "json-rpc",
    "rpc-client",
    # "rpc-types",
    "rpc-types-eth",
    # "rpc-types-engine",
    "rpc-types-trace",
    "signers",
    # "signer-aws",
    # "signer-gcp",
    "signer-keystore",
    "signer-ledger",
    "signer-mnemonic",
    "signer-trezor",
    "signer-wallet",
    "signer-yubihsm",
    "transports",
    "transport-http",
    "transport-ipc",
    "transport-ws",
    "pubsub",
] }

prometheus = { path = "../../libs/prometheus" }

reqwest = { version = "0.12", features = ["multipart", "blocking"] }
# async
tokio = { version = "1.4.0", features = ["full"] }

# misc
eyre = "0.6.12"
openssl-sys = "0.9.102"
actix-web = "4.6.0"
actix-multipart = "0.7.2"
actix-test = "0.1.5"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"]}
futures = "0.3.30"
envload = "0.1.1"
once_cell = "1.20.0"
async-channel = "2.3.0"
tracing = { version = "0.1.40", features = ["async-await", "log"] }
tracing-subscriber = { version = "0.3.18", features = ["json"] }
bytes = "1.6.0"
futures-util = "0.3.30"
rand = "0.8.5"
paste = "1.0.15"
regex = "1.10.4"
tempfile = "3.10.1"
time = "0.3.36"
conv = "0.3.3"
uuid = { version = "1.8.0", features = ["v4"] }
chrono = "0.4.38"
ringbuf = "0.4.0"

[[bin]]
name = "sequencer"
path = "bin/sequencer_runner.rs"
