[package]
name = "trigger-oracle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus = { path = "../../libs/prometheus" }
data_feeds = { path = "../../libs/data_feeds"}
feed_registry = { path = "../../libs/feed_registry"}
crypto = { path = "../../libs/crypto"}
utils = { path = "../../libs/utils"}

anyhow = "1.0.89"
clap = { version = "3.1.15", features = ["derive", "env"] }
futures = "0.3"
is-terminal = "0.4.12"
log = "0.4.21"
reqwest = { version = "0.12", features=["json"] }
serde = "1.0"
serde_json = "1.0"

spin-app = { git = "https://github.com/blocksense-network/spin", branch="blocksense"}
spin-core = { git = "https://github.com/blocksense-network/spin", branch="blocksense"}
spin-trigger = { git = "https://github.com/blocksense-network/spin", branch="blocksense"}
spin-outbound-networking = { git = "https://github.com/blocksense-network/spin", branch="blocksense"}
terminal = { git = "https://github.com/blocksense-network/spin", branch="blocksense"}
outbound-http = { git = "https://github.com/blocksense-network/spin", branch="blocksense"}

tokio = { version = "1.11", features = ["full"] }
tokio-scoped = "0.2.0"
tracing = { version = "0.1.40" , features=["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
http = "1.1.0"
hyper = "1.3.1"
wasmtime = "22.0.0"
wasmtime-wasi = "22.0.0"
wasmtime-wasi-http = "22.0.0"
