spin_manifest_version = 2

[application]
authors = ["Yordan Madzhunkov"]
name = "Exsat network btc holdings"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 600
sequencer = "http://127.0.0.1:9856/post_reports_batch"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
reporter_id = 0

[[trigger.oracle]]
component = "exsat-holdings"

[[trigger.oracle.data_feeds]]
id = "100000"
data = '{"pair":{"base":"Exsat","quote":"satoshi"},"decimals":0,"category":"Crypto","market_hours":"Crypto","arguments":{}}'


[component.exsat-holdings]
source = "../../../target/wasm32-wasip1/release/exsat_holdings.wasm"
key_value_stores = ["default"]
allowed_outbound_hosts = [
    "https://raw.githubusercontent.com",
    "https://rpc-us.exsat.network",
    "https://blockchain.info",
    "https://mempool.space",
]

[component.exsat-holdings.build]
command = "cargo build --target wasm32-wasip1 --release"
