spin_manifest_version = 2

[application]
authors = ["Emil Ivanichkov"]
name = "Hyper"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 3
reporter_id = 0
sequencer = "http://127.0.0.1:8877/post_reports_batch"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
second_consensus_secret_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
kafka_endpoint = "http://127.0.0.1:9092"

[[trigger.oracle]]
component = "borrow-rates"
interval_time_in_seconds = 3
capabilities = []


[[trigger.oracle.data_feeds]]
id = "102001"
stride = 0
decimals = 18
data = '{"pair":{"base":"WHYPE","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"HypurrFi","network":"hyperevm-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102002"
stride = 0
decimals = 18
data = '{"pair":{"base":"wstHYPE","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"HypurrFi","network":"hyperevm-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102003"
stride = 0
decimals = 18
data = '{"pair":{"base":"UBTC","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"HypurrFi","network":"hyperevm-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102004"
stride = 0
decimals = 18
data = '{"pair":{"base":"UETH","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"HypurrFi","network":"hyperevm-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102005"
stride = 0
decimals = 18
data = '{"pair":{"base":"USDe","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"HypurrFi","network":"hyperevm-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102051"
stride = 0
decimals = 18
data = '{"pair":{"base":"WHYPE","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"HyperLend","network":"hyperevm-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102052"
stride = 0
decimals = 18
data = '{"pair":{"base":"wstHYPE","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"HyperLend","network":"hyperevm-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102053"
stride = 0
decimals = 18
data = '{"pair":{"base":"UBTC","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"HyperLend","network":"hyperevm-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102054"
stride = 0
decimals = 18
data = '{"pair":{"base":"UETH","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"HyperLend","network":"hyperevm-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102055"
stride = 0
decimals = 18
data = '{"pair":{"base":"USDe","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"HyperLend","network":"hyperevm-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102101"
stride = 0
decimals = 18
data = '{"pair":{"base":"HYPE","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"1","marketplace":"HyperDrive"}}'

[[trigger.oracle.data_feeds]]
id = "102102"
stride = 0
decimals = 18
data = '{"pair":{"base":"USDe","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"2","marketplace":"HyperDrive"}}'

[[trigger.oracle.data_feeds]]
id = "102103"
stride = 0
decimals = 18
data = '{"pair":{"base":"USD₮0","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"3","marketplace":"HyperDrive"}}'

[[trigger.oracle.data_feeds]]
id = "102104"
stride = 0
decimals = 18
data = '{"pair":{"base":"USDhl","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"5","marketplace":"HyperDrive"}}'

[[trigger.oracle.data_feeds]]
id = "102151"
stride = 0
decimals = 18
data = '{"pair":{"base":"USDC","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"EulerFinance","network":"ethereum-mainnet","utils_lens_address":"0xB8cac3e5CaaC2042B79938aFe7FEA3f44e5afcC1","vault_address":"0xe0a80d35bB6618CBA260120b279d357978c42BCE"}}'

[[trigger.oracle.data_feeds]]
id = "102152"
stride = 0
decimals = 18
data = '{"pair":{"base":"USDT","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"EulerFinance","network":"ethereum-mainnet","utils_lens_address":"0xB8cac3e5CaaC2042B79938aFe7FEA3f44e5afcC1","vault_address":"0x7c280DBDEf569e96c7919251bD2B0edF0734C5A8"}}'

[[trigger.oracle.data_feeds]]
id = "102153"
stride = 0
decimals = 18
data = '{"pair":{"base":"WETH","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"EulerFinance","network":"ethereum-mainnet","utils_lens_address":"0xB8cac3e5CaaC2042B79938aFe7FEA3f44e5afcC1","vault_address":"0xD8b27CF359b7D15710a5BE299AF6e7Bf904984C2"}}'

[[trigger.oracle.data_feeds]]
id = "102201"
stride = 0
decimals = 18
data = '{"pair":{"base":"WETH","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"Aave","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102202"
stride = 0
decimals = 18
data = '{"pair":{"base":"weETH","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"Aave","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102203"
stride = 0
decimals = 18
data = '{"pair":{"base":"USDT","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"Aave","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102204"
stride = 0
decimals = 18
data = '{"pair":{"base":"wstETH","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"Aave","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102205"
stride = 0
decimals = 18
data = '{"pair":{"base":"USDC","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","marketplace":"Aave","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102251"
stride = 0
decimals = 18
data = '{"pair":{"base":"cbBTC / USDC","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"0x64d65c9a2d91c36d56fbc42d69e979335320169b3df63bf92789e2c8883fcc64","marketplace":"Morpho","morpho_core_address":"0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102252"
stride = 0
decimals = 18
data = '{"pair":{"base":"srUSD / USDC","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"0xbfed072faee09b963949defcdb91094465c34c6c62d798b906274ef3563c9cac","marketplace":"Morpho","morpho_core_address":"0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102253"
stride = 0
decimals = 18
data = '{"pair":{"base":"WBTC / USDC","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"0x3a85e619751152991742810df6ec69ce473daef99e28a64ab2340d7b7ccfee49","marketplace":"Morpho","morpho_core_address":"0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102254"
stride = 0
decimals = 18
data = '{"pair":{"base":"ETH+ / WETH","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"0x5f8a138ba332398a9116910f4d5e5dcd9b207024c5290ce5bc87bc2dbd8e4a86","marketplace":"Morpho","morpho_core_address":"0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102255"
stride = 0
decimals = 18
data = '{"pair":{"base":"wstETH / WETH","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"0xb8fc70e82bc5bb53e773626fcc6a23f7eefa036918d7ef216ecfb1950a94a85e","marketplace":"Morpho","morpho_core_address":"0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102256"
stride = 0
decimals = 18
data = '{"pair":{"base":"weETH / WETH","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"0x37e7484d642d90f14451f1910ba4b7b8e4c3ccdd0ec28f8b2bdb35479e472ba7","marketplace":"Morpho","morpho_core_address":"0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102257"
stride = 0
decimals = 18
data = '{"pair":{"base":"mHYPER / USDC","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"0x95c28d447950ca6c8bbfd25fc05b80b1fd7a1cdd17a3610b4b3f1ffc8dc2e2ed","marketplace":"Morpho","morpho_core_address":"0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102258"
stride = 0
decimals = 18
data = '{"pair":{"base":"PT-cUSDO-20NOV2025 / USDC","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"0x8a71a66ac828c2b6d4f8accce5859aba0822b502f3833bec4aff09479affffdb","marketplace":"Morpho","morpho_core_address":"0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102259"
stride = 0
decimals = 18
data = '{"pair":{"base":"WBTC / USDT","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"0xa921ef34e2fc7a27ccc50ae7e4b154e16c9799d3387076c421423ef52ac4df99","marketplace":"Morpho","morpho_core_address":"0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb","network":"ethereum-mainnet"}}'

[[trigger.oracle.data_feeds]]
id = "102260"
stride = 0
decimals = 18
data = '{"pair":{"base":"wstETH / USDC","quote":""},"decimals":18,"category":"Rates","market_hours":"","arguments":{"kind":"borrow-rates","market_id":"0xb323495f7e4148be5643a4ea4a8221eef163e4bccfdedc2a6f4696baacbc86cc","marketplace":"Morpho","morpho_core_address":"0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb","network":"ethereum-mainnet"}}'

[component.borrow-rates]
source = "../target/wasm32-wasip1/release/borrow_rates.wasm"
allowed_outbound_hosts = [
  "https://rpc.hyperliquid.xyz",
  "https://api.hyperdrive.fi",
  "https://eth.llamarpc.com",
  "https://eth.blockrazor.xyz",
]

[component.borrow-rates.build]
command = "cargo build --target wasm32-wasip1 --release"
