spin_manifest_version = 2

[application]
authors = ["Mila Genova", "Emil Ivanichkov"]
name = "Forex Price Feeds Oracle"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 10
sequencer = "http://127.0.0.1:9856/post_reports_batch"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
second_consensus_secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
kafka_endpoint = "http://127.0.0.1:9092"
reporter_id = 0

[[trigger.oracle]]
component = "forex-price-feeds"

[[trigger.oracle.data_feeds]]
id = "0"
stride = 0
decimals = 8
data = 'dummy'

[component.forex-price-feeds]
source = "../target/wasm32-wasip1/release/forex_price_feeds.wasm"
allowed_outbound_hosts = []

[component.forex-price-feeds.build]
command = "cargo build --target wasm32-wasip1 --release"
