[package]
name = "stock-price-feeds"
authors = ["Mila Genova", "Emil Ivanichkov"]
description = "Oracle script delivering up-to-date stock market price feeds from multiple financial data providers."
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
blocksense-data-providers-sdk = { workspace = true }
blocksense-sdk = { workspace = true }

anyhow = { workspace = true }
chrono = "0.4"
chrono-tz = "0.8"
futures = { workspace = true }
itertools = { workspace = true }
prettytable-rs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde-this-or-that = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
wit-bindgen = { workspace = true }
