[package]
name = "stock-price-feeds"
authors = ["Mila Genova", "Emil Ivanichkov"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }
blocksense-sdk = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde-this-or-that = { workspace = true }
prettytable-rs = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
chrono = "0.4"
chrono-tz = "0.8"
