spin_manifest_version = 2

[application]
authors = ["Mila Genova", "Emil Ivanichkov"]
name = " Stock Price Feeds Oracle"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 10
sequencer = "http://127.0.0.1:9856/post_reports_batch"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
second_consensus_secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
kafka_endpoint = "http://127.0.0.1:9092"
reporter_id = 0

[[trigger.oracle]]
component = "stock-price-feeds"

[[trigger.oracle.data_feeds]]
id = "2000000"
stride = 0
decimals = 8
data = '{"pair":{"base":"IBIT","quote":"USD"},"decimals":8,"category":"Equities","provider_hours":"US_Equities","arguments":{"providers":["AlphaVantage","PolygonIO","Finnhum","YahooFinance","twelvedata","Tiingo","FMP"]}}'

[[trigger.oracle.data_feeds]]
id = "2000001"
stride = 0
decimals = 8
data = '{"pair":{"base":"SPY","quote":"USD"},"decimals":8,"category":"Equities","provider_hours":"US_Equities","arguments":{"providers":["AlphaVantage","PolygonIO","Finnhum","YahooFinance","twelvedata","Tiingo","FMP"]}}'

[component.stock-price-feeds]
source = "../../../target/wasm32-wasip1/release/stock_price_feeds.wasm"
allowed_outbound_hosts = [
  "https://www.alphavantage.co",
]

[component.stock-price-feeds.build]
command = "cargo build --target wasm32-wasip1 --release"
