[package]
name = "sequencer_tests"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
data_feeds = { path = "../../libs/data_feeds" }
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "6f4e397f7cf71812160a165bdcebf40cac814fef", features = [
    # "dyn-abi",
    # "json-abi",
    # "json",
    "sol-types",
    # "rlp",
    # "serde",
    "contract",
    # "consensus",
    # "eips",
    "network",
    # "genesis",
    "node-bindings",
    "providers",
    "rpc",
    # "json-rpc",
    "rpc-client",
    # "rpc-types",
    "rpc-types-eth",
    # "rpc-types-engine",
    "rpc-types-trace",
    "signers",
    # "signer-aws",
    # "signer-gcp",
    "signer-keystore",
    "signer-ledger",
    "signer-mnemonic",
    "signer-trezor",
    "signer-wallet",
    "signer-yubihsm",
    "transports",
    "transport-http",
    "transport-ipc",
    "transport-ws",
    "pubsub",
] }

reqwest = { version = "0.12", default-features = false }
# async
tokio = { version = "1.4.0", features = ["full"] }

# misc
eyre = "0.6.12"
serde = { version = "1.0.203", features = ["derive"]}
futures = "0.3.30"
tracing = { version = "0.1.40", features = ["async-await", "log"] }
url = "2.5.2"
port_scanner = "0.1.5"
curl = "0.4.46"
serde_json = "1.0.117"

[[bin]]
name = "sequencer_tests"
path = "bin/sequencer_tests.rs"
