name: Trigger actions on push to main

on:
  push:
    branches:
      - main

env:
  DFCG_ARTIFACTS_ACCESS_TOKEN: ${{ secrets.DFCG_ARTIFACTS_ACCESS_TOKEN }}
  RPC_URL_ETHEREUM_SEPOLIA: ${{ secrets.RPC_URL_ETHEREUM_SEPOLIA }}
  RPC_URL_INK_SEPOLIA: ${{ secrets.RPC_URL_INK_SEPOLIA }}
  X: ${{ secrets.X }}

jobs:
  deploy_websites:
    name: Deploy ${{ matrix.project }} website
    timeout-minutes: 10
    runs-on: [self-hosted, nixos, x86-64-v3]
    strategy:
      matrix:
        include:
          - project: docs.blocksense.network
            path: apps/docs.blocksense.network/dist
            project_name: blocksense-docs
            build_command: yarn workspace @blocksense/docs.blocksense.network build:with-deps
          - project: docs-ui.blocksense.network
            path: libs/ts/docs-ui/storybook-static
            project_name: blocksense-docs-ui
            build_command: yarn workspace @blocksense/docs-ui build-storybook
          - project: ui.blocksense.network
            path: libs/ts/ui/storybook-static
            project_name: blocksense-ui
            build_command: yarn workspace @blocksense/ui build-storybook
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/cachix-action@v16
        with:
          name: ${{ vars.CACHIX_CACHE }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build & activate the Nix Dev Shell
        run: |
          eval "$(nix print-dev-env --accept-flake-config --impure .#devShells.x86_64-linux.js || echo exit 1)"
          env >> "$GITHUB_ENV"

      - name: Install JS deps
        run: yarn install

      - name: Build
        env:
          NEXT_PUBLIC_VERIFICATION_API_KEY: ${{ secrets.NEXT_PUBLIC_VERIFICATION_API_KEY }}
          NEXT_PUBLIC_VERIFICATION_API_URL: ${{ secrets.NEXT_PUBLIC_VERIFICATION_API_URL }}
        id: build
        run: ${{ matrix.build_command }}

      - name: Deploy Website
        id: deploy-website
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages deploy ${{ matrix.path }} --project-name=${{ matrix.project_name }}
