name: Trigger actions on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy_websites:
    name: Deploy ${{ matrix.project }} website
    timeout-minutes: 10
    runs-on: [self-hosted, nixos, x86-64-v3]
    strategy:
      matrix:
        include:
          - project: docs.blocksense.network
            path: apps/docs.blocksense.network/dist
            project_name: blocksense
            build_command: yarn workspace @blocksense/docs.blocksense.network build:with-deps
          - project: ui.blocksense.network
            path: libs/ts/ui/storybook-static
            project_name: blocksense-ui
            build_command: yarn workspace @blocksense/ui build-storybook
          - project: nft.blocksense.network
            path: apps/nft.blocksense.network/out
            project_name: blocksense-nft
            build_command: yarn workspace @blocksense/nft.blocksense.network build
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/cachix-action@v16
        with:
          name: ${{ vars.CACHIX_CACHE }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build & activate the Nix Dev Shell
        run: |
          eval "$(nix print-dev-env --accept-flake-config --impure .#devShells.x86_64-linux.js || echo exit 1)"
          env >> "$GITHUB_ENV"

      - name: Install JS deps
        run: yarn install

      - name: Build
        id: build
        run: ${{ matrix.build_command }}

      - name: Deploy Website
        id: deploy-website
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages deploy ${{ matrix.path }} --project-name=${{ matrix.project_name }}

  downstream-flake-update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - downstream-repo: 'blocksense-network/infra'
    steps:
      - uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.NIX_FLAKE_UPDATE_PR_BOT_APP_ID }}
          private_key: ${{ secrets.NIX_FLAKE_UPDATE_PR_BOT_APP_PRIVATE_KEY }}

      - name: Trigger Downstream Pipeline
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ steps.generate-token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28"  \
            "https://api.github.com/repos/${{ matrix.downstream-repo }}/dispatches" \
            -d '{
              "event_type": "flake-update",
              "client_payload":{"branch-trigger": "${{ github.ref_name }}"}
            }'
