name: Trigger Downstream Flake Update on Push to Main

on:
  push:
    branches:
      - main
      - testnet
      - mainnet

jobs:
  downstream-flake-update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - downstream-repo: 'blocksense-network/infra'
    steps:
      - name: Compare nix outputs
        id: compare
        run: |
          # Get current output
          CURRENT_OUTPUT="$(just eval-machine "example-setup-01")"
          echo "After: '$CURRENT_OUTPUT'"

          # Get previous commit output
          PREVIOUS_OUTPUT="$(just eval-machine "example-setup-01" "${{ github.event.before }}")"
          echo "Before: '$PREVIOUS_OUTPUT'"

          # Set output variable
          if [ "$CURRENT_OUTPUT" != "$PREVIOUS_OUTPUT" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - uses: tibdex/github-app-token@v2.1.0
        if: steps.compare.outputs.changed == 'true'
        id: generate-token
        with:
          app_id: ${{ secrets.NIX_FLAKE_UPDATE_PR_BOT_APP_ID }}
          private_key: ${{ secrets.NIX_FLAKE_UPDATE_PR_BOT_APP_PRIVATE_KEY }}

      - name: Trigger Downstream Pipeline
        if: steps.compare.outputs.changed == 'true'
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ steps.generate-token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28"  \
            "https://api.github.com/repos/${{ matrix.downstream-repo }}/dispatches" \
            -d '{
              "event_type": "flake-update",
              "client_payload":{"branch-trigger": "${{ github.ref_name }}"}
            }'
